name: Android APK CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:

#env:
  #VLC_ANDROID_IMAGE_40: registry.videolan.org/vlc-debian-android:20250626142950

jobs:
  build-apk:
    runs-on: ubuntu-latest
    container:
      image: registry.videolan.org/vlc-debian-android:20250626142950
    steps:
      - uses: actions/checkout@v4

      #- name: 配置 Android Keystore（如有需要）
      #  if: env.KEYSTORE_FILE_BASE64 != ''
      #  run: |
      #    mkdir -p ~/.android
      #    echo "$KEYSTORE_FILE_BASE64" | base64 -d > ~/.android/debug.keystore

      - name: 初始化编译环境
        run: ./buildsystem/compile.sh --init

      - name: 编译 APK
        run: ./gradlew assembleDebug

      - name: 上传 APK 产物
        uses: actions/upload-artifact@v4
        with:
          name: vlc-android-apk
          path: application/app/build/outputs/apk/debug/*.apk

  release:
    runs-on: ubuntu-latest
    container:
      image: registry.videolan.org/vlc-debian-android:20250626142950
    needs: build-apk
    #if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      #- name: 配置 Android Keystore（如有需要）
      #  if: env.KEYSTORE_FILE_BASE64 != ''
      #  run: |
      #    mkdir -p ~/.android
      #    echo "$KEYSTORE_FILE_BASE64" | base64 -d > ~/.android/debug.keystore

      - name: 初始化编译环境
        run: ./buildsystem/compile.sh --init

      - name: 编译 Release APK/Bundles
        run: |
          ./gradlew assembleRelease
          ./gradlew bundleVlcBundle
          ./gradlew bundleVlcBundleAmazon

      - name: 上传 Release 产物
        uses: actions/upload-artifact@v4
        with:
          name: vlc-android-release
          path: |
            application/app/build/outputs/apk/release/VLC-Android-*.apk
            application/app/build/outputs/bundle/vlcBundle/*.aab
            application/app/build/outputs/bundle/vlcBundleAmazon/*.aab