name: Build VLC for Android

on:
  workflow_dispatch:
  #push:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      LANG: zh_CN.UTF-8
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      #ANDROID_NDK_VERSION: "27.4.7075529"   # NDK r27
      ABI: "arm64"   # 可根据需求调整，比如 "all"、"arm"、"x86" 等

    steps:
    - name: 汉化
      run: |
        sudo apt-get update
        sudo apt-get install language-pack-zh-hans
        
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 检出代码1
      run: git submodule update --init --recursive

    - name: 安装依赖
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -y automake ant autopoint cmake build-essential libtool-bin \
          patch pkg-config protobuf-compiler ragel subversion unzip git \
          openjdk-8-jre openjdk-8-jdk flex wget \
          zlib1g:i386 libstdc++6:i386 libc6:i386

    - name: 设置 JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '17'

    - name: 安装 Android SDK
      uses: android-actions/setup-android@v3
      with:
        sdk-version: "28"

    - name: 安装 Android NDK r27
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r27d-linux.zip
        unzip android-ndk-r27d-linux.zip
        mv android-ndk-r27d ${{ github.workspace }}/android-ndk
        echo "ANDROID_NDK=${{ github.workspace }}/android-ndk" >> $GITHUB_ENV

    - name: 配置环境变量
      run: |
        echo "ANDROID_SDK=${ANDROID_SDK_ROOT}" >> $GITHUB_ENV
        echo "ANDROID_NDK=${{ github.workspace }}/android-ndk" >> $GITHUB_ENV
        echo "$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/tools" >> $GITHUB_PATH

    #- name: 拉取 VLC 源码（如 workflow 不在主仓库，可加此步）
    #  if: ${{ !env.ACT }} # 本地 act 测试时跳过
    #  run: |
    #    git clone https://code.videolan.org/videolan/vlc-android.git vlc-android
    #    cd vlc-android
    #    git submodule update --init --recursive

    - name: 设置 git 身份
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: 预编译（初始化 Gradle 构建环境）
      run: |
        chmod +x buildsystem/compile.sh
        #./buildsystem/compile.sh -l -a $ABI
        ./buildsystem/compile.sh -l

    - name: 编译 debug APK
      run: |
        ./gradlew assembleDebug

    - name: 上传 APK 到 workflow artifacts
      uses: actions/upload-artifact@v4
      with:
        name: vlc-android-apk
        path: application/build/outputs/apk/debug/*.apk
